using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
using SystemChecker.Converters;
using SystemChecker.Services;

namespace SystemChecker;

public partial class TelemetryMainWindow
{
    private readonly ProcessMonitorService _processService=new();private readonly ObservableCollection<ProcessItem> _processes=[];private DispatcherTimer? _processTimer;private DataGrid? _processGrid;private FrameworkElement? _processPage;private Button? _processNav;private bool _processRefreshing;
    private void EnhanceBenchmarkReference()
    {
        if(BenchmarkPage.Content is not StackPanel root)return;var panel=Panel();panel.Margin=new Thickness(0,12,0,0);var stack=new StackPanel();panel.Child=stack;stack.Children.Add(Heading("PERFORMANCE REFERENCE"));stack.Children.Add(new TextBlock{Text="절대 순위가 아닌 재현 가능한 처리량 기준입니다. 같은 CoreWatch 버전과 전원 설정에서 비교하세요.",Foreground=new SolidColorBrush(Color.FromRgb(104,112,125)),Margin=new Thickness(0,6,0,12)});var converter=new PerformanceTierConverter();foreach(var entry in new[]{("CPU",nameof(ViewModels.TelemetryV4ViewModel.CpuScoreBar)),("MEMORY",nameof(ViewModels.TelemetryV4ViewModel.MemoryScoreBar)),("DISK",nameof(ViewModels.TelemetryV4ViewModel.DiskScoreBar)),("GPU",nameof(ViewModels.TelemetryV4ViewModel.GpuScoreBar))}){var row=new Grid{Margin=new Thickness(0,5,0,5)};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(90)});row.ColumnDefinitions.Add(new ColumnDefinition());row.Children.Add(new TextBlock{Text=entry.Item1,FontFamily=new FontFamily("Consolas"),FontWeight=FontWeights.SemiBold});var result=new TextBlock{Foreground=new SolidColorBrush(Color.FromRgb(82,90,102))};result.SetBinding(TextBlock.TextProperty,new Binding(entry.Item2){Converter=converter,ConverterParameter=entry.Item1});Grid.SetColumn(result,1);row.Children.Add(result);stack.Children.Add(row);}root.Children.Add(panel);
        var hardware=Panel();hardware.Margin=new Thickness(0,12,0,0);var hs=new StackPanel();hardware.Child=hs;hs.Children.Add(Heading("TESTED HARDWARE / PERFORMANCE CONTEXT"));hs.Children.Add(new TextBlock{Text="CPU, GPU, 메모리, 메인보드와 저장장치 구성을 점수와 함께 기록합니다.",Foreground=new SolidColorBrush(Color.FromRgb(104,112,125)),Margin=new Thickness(0,6,0,10)});var data=new DataGrid{ItemsSource=_viewModel.HardwareItems,AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false,Height=260};data.Columns.Add(new DataGridTextColumn{Header="분류",Binding=new Binding("Category"),Width=120});data.Columns.Add(new DataGridTextColumn{Header="하드웨어",Binding=new Binding("Name"),Width=new DataGridLength(2,DataGridLengthUnitType.Star)});data.Columns.Add(new DataGridTextColumn{Header="사양",Binding=new Binding("Value"),Width=new DataGridLength(3,DataGridLengthUnitType.Star)});hs.Children.Add(data);root.Children.Add(hardware);
    }
    private void EnhanceReportContents()
    {
        var panel=Panel();panel.Margin=new Thickness(0,12,0,0);var stack=new StackPanel();panel.Child=stack;stack.Children.Add(Heading("REPORT DATASET"));stack.Children.Add(new TextBlock{Text="보고서는 화면 캡처가 아니라 아래 원시 데이터와 산식을 포함한 진단 문서입니다.",Foreground=new SolidColorBrush(Color.FromRgb(104,112,125)),Margin=new Thickness(0,6,0,12)});var grid=new Grid();for(var i=0;i<3;i++)grid.ColumnDefinitions.Add(new ColumnDefinition());AddDataset(grid,0,"SYSTEM","하드웨어 인벤토리\nSMART · 배터리 · 드라이버");AddDataset(grid,1,"PERFORMANCE","CPU · 메모리 · DiskSpd · GPU\n최근 60초 텔레메트리");AddDataset(grid,2,"HISTORY","SQLite 벤치마크 이력\n이전 점수 비교");stack.Children.Add(grid);ReportPage.Children.Insert(Math.Min(3,ReportPage.Children.Count),panel);
    }
    private static void AddDataset(Grid grid,int column,string title,string detail){var border=new Border{Background=new SolidColorBrush(Color.FromRgb(248,249,251)),BorderBrush=new SolidColorBrush(Color.FromRgb(222,226,232)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(4),Padding=new Thickness(14),Margin=new Thickness(column==0?0:5,0,column==2?0:5,0)};var s=new StackPanel();s.Children.Add(new TextBlock{Text=title,FontSize=10,FontWeight=FontWeights.SemiBold});s.Children.Add(new TextBlock{Text=detail,FontSize=10,Foreground=new SolidColorBrush(Color.FromRgb(104,112,125)),Margin=new Thickness(0,6,0,0),TextWrapping=TextWrapping.Wrap});border.Child=s;Grid.SetColumn(border,column);grid.Children.Add(border);}
    private void InitializeProcessPage()
    {
        if(OverviewPage.Parent is not Grid host||ReportNav.Parent is not StackPanel navHost)return;_processNav=new Button{Style=(Style)FindResource("Nav"),CommandParameter="Processes"};_processNav.Content=new StackPanel{Orientation=Orientation.Horizontal,Children={new TextBlock{Text="05",FontFamily=new FontFamily("Consolas"),FontSize=10,Width=28},new TextBlock{Text="PROCESSES",FontSize=11,FontWeight=FontWeights.SemiBold}}};_processNav.Click+=ProcessNav_Click;navHost.Children.Add(_processNav);foreach(var b in new[]{OverviewNav,HardwareNav,BenchmarkNav,ReportNav})b.Click+=(_,_)=>{if(_processPage is not null)_processPage.Visibility=Visibility.Collapsed;if(_processNav is not null)_processNav.Tag=null;};
        var page=new Grid{Visibility=Visibility.Collapsed};page.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});page.RowDefinitions.Add(new RowDefinition());var header=new Grid{Margin=new Thickness(0,0,0,14)};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var titles=new StackPanel();titles.Children.Add(new TextBlock{Text="RUNNING PROCESSES",FontSize=20,FontWeight=FontWeights.SemiBold});titles.Children.Add(new TextBlock{Text="CPU·메모리 점유율, 보호 등급과 종료 가능 여부를 함께 표시합니다.",Foreground=new SolidColorBrush(Color.FromRgb(104,112,125)),Margin=new Thickness(0,5,0,0)});header.Children.Add(titles);var actions=new StackPanel{Orientation=Orientation.Horizontal};var search=new TextBox{Width=240,Height=36,Padding=new Thickness(10,7,10,7),Margin=new Thickness(0,0,8,0),ToolTip="프로세스명, PID, 분류 또는 경로 검색"};search.TextChanged+=(_,_)=>CollectionViewSource.GetDefaultView(_processes).Refresh();var view=CollectionViewSource.GetDefaultView(_processes);view.Filter=o=>o is ProcessItem p&&(string.IsNullOrWhiteSpace(search.Text)||$"{p.Name} {p.Id} {p.Classification} {p.Detail}".Contains(search.Text,StringComparison.OrdinalIgnoreCase));actions.Children.Add(search);actions.Children.Add(Action("새로고침",async(_,_)=>await RefreshProcessesAsync()));actions.Children.Add(Action("선택 프로세스 종료",TerminateProcess_Click,"#A93D3D","#FFFFFF"));Grid.SetColumn(actions,1);header.Children.Add(actions);page.Children.Add(header);
        _processGrid=new DataGrid{ItemsSource=_processes,AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false,CanUserSortColumns=true,SelectionMode=DataGridSelectionMode.Single};_processGrid.Columns.Add(new DataGridTextColumn{Header="프로세스",Binding=new Binding("Name"),SortMemberPath="Name",Width=new DataGridLength(2,DataGridLengthUnitType.Star)});_processGrid.Columns.Add(new DataGridTextColumn{Header="PID",Binding=new Binding("Id"),SortMemberPath="Id",Width=80});_processGrid.Columns.Add(new DataGridTextColumn{Header="CPU %",Binding=new Binding("CpuPercent"){StringFormat="{0:0.0}"},SortMemberPath="CpuPercent",Width=90});_processGrid.Columns.Add(new DataGridTextColumn{Header="메모리 MB",Binding=new Binding("MemoryMb"){StringFormat="{0:N0}"},SortMemberPath="MemoryMb",Width=110});_processGrid.Columns.Add(new DataGridTextColumn{Header="보호 등급",Binding=new Binding("Classification"),SortMemberPath="Classification",Width=135});_processGrid.Columns.Add(new DataGridTextColumn{Header="실행 경로 / 판단 근거",Binding=new Binding("Detail"),SortMemberPath="Detail",Width=new DataGridLength(3,DataGridLengthUnitType.Star)});Grid.SetRow(_processGrid,1);page.Children.Add(_processGrid);host.Children.Add(page);_processPage=page;
        _processTimer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};_processTimer.Tick+=async(_,_)=>{if(_processPage?.Visibility==Visibility.Visible)await RefreshProcessesAsync();};Loaded+=async(_,_)=>{_processTimer.Start();await RefreshProcessesAsync();};Closed+=(_,_)=>_processTimer.Stop();
    }
    private async void ProcessNav_Click(object sender,RoutedEventArgs e){OverviewPage.Visibility=HardwarePage.Visibility=BenchmarkPage.Visibility=ReportPage.Visibility=Visibility.Collapsed;if(_processPage is not null)_processPage.Visibility=Visibility.Visible;OverviewNav.Tag=HardwareNav.Tag=BenchmarkNav.Tag=ReportNav.Tag=null;if(_processNav is not null)_processNav.Tag="Active";PageTitle.Text="PROCESSES";await RefreshProcessesAsync();}
    private async Task RefreshProcessesAsync(){if(_processRefreshing)return;_processRefreshing=true;try{var selected=(_processGrid?.SelectedItem as ProcessItem)?.Id;var items=await _processService.CaptureAsync(_monitorCancellation.Token);_processes.Clear();foreach(var item in items)_processes.Add(item);if(selected.HasValue&&_processGrid is not null)_processGrid.SelectedItem=_processes.FirstOrDefault(x=>x.Id==selected);}catch(OperationCanceledException){}finally{_processRefreshing=false;}}
    private async void TerminateProcess_Click(object sender,RoutedEventArgs e){if(_processGrid?.SelectedItem is not ProcessItem item){MessageBox.Show(this,"종료할 프로세스를 선택하세요.","CoreWatch");return;}if(!item.CanTerminate){MessageBox.Show(this,$"{item.Name}은(는) '{item.Classification}'으로 분류되어 CoreWatch에서 종료하지 않습니다.","보호된 프로세스",MessageBoxButton.OK,MessageBoxImage.Warning);return;}if(MessageBox.Show(this,$"{item.Name} (PID {item.Id})을 종료하시겠습니까?\n저장하지 않은 작업이 손실될 수 있습니다.","프로세스 종료 확인",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;try{await _processService.TerminateAsync(item,_monitorCancellation.Token);await RefreshProcessesAsync();}catch(Exception ex){MessageBox.Show(this,ex.Message,"종료 실패",MessageBoxButton.OK,MessageBoxImage.Error);}}
}
