using Microsoft.Win32;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using SystemChecker.ViewModels;
using Forms = System.Windows.Forms;

namespace SystemChecker;

public partial class TelemetryMainWindow : Window
{
    private readonly TelemetryV4ViewModel _viewModel=new();private readonly CancellationTokenSource _monitorCancellation=new();private CancellationTokenSource? _benchmarkCancellation;private Task? _monitorTask;private bool _sidebarCollapsed,_benchmarkActive,_allowClose;private readonly Forms.NotifyIcon _tray;private DateTimeOffset _lastAlert=DateTimeOffset.MinValue;
    public TelemetryMainWindow()
    {
        InitializeComponent();BuildExtendedUi();ForceProgressBindingsOneWay();DataContext=_viewModel;
        _tray=new Forms.NotifyIcon{Icon=System.Drawing.SystemIcons.Application,Text="System Checker",Visible=true};_tray.DoubleClick+=(_,_)=>RestoreFromTray();var menu=new Forms.ContextMenuStrip();menu.Items.Add("열기",null,(_,_)=>RestoreFromTray());menu.Items.Add("종료",null,(_,_)=>{_allowClose=true;Close();});_tray.ContextMenuStrip=menu;
        Loaded+=OnLoaded;Closed+=OnClosed;StateChanged+=(_,_)=>{if(WindowState==WindowState.Minimized)HideToTray();};
    }
    private void BuildExtendedUi()
    {
        if(BenchmarkPage.Content is StackPanel bench)
        {
            var panel=Panel();panel.Margin=new Thickness(0,12,0,0);var stack=new StackPanel();panel.Child=stack;stack.Children.Add(Heading("STORAGE / GPU BREAKDOWN"));stack.Children.Add(Metric("DISK · MICROSOFT DISKSPD",nameof(TelemetryV4ViewModel.DiskBenchmarkText),nameof(TelemetryV4ViewModel.DiskScoreBar),"#D47832"));stack.Children.Add(Metric("GPU · DIRECT3D RENDER",nameof(TelemetryV4ViewModel.GpuBenchmarkText),nameof(TelemetryV4ViewModel.GpuScoreBar),"#249467"));bench.Children.Add(panel);
            var historyPanel=Panel();historyPanel.Margin=new Thickness(0,12,0,0);var hs=new StackPanel();historyPanel.Child=hs;hs.Children.Add(Heading("PREVIOUS RESULTS / COMPARISON"));var grid=CreateHistoryGrid();grid.Height=230;hs.Children.Add(grid);bench.Children.Add(historyPanel);
        }
        ReportPage.MaxWidth=double.PositiveInfinity;ReportPage.Width=double.NaN;
        var controls=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,12,0,12)};controls.Children.Add(Action("PDF 보고서",ExportPdf_Click));controls.Children.Add(Action("HTML 보고서",ExportHtml_Click));controls.Children.Add(Action("상태 새로고침",RefreshHealth_Click,"#E4E7EB","#303640"));ReportPage.Children.Add(controls);
        var health=Panel();var content=new StackPanel();health.Child=content;content.Children.Add(Heading("SMART / STORAGE RELIABILITY"));var dg=new DataGrid{ItemsSource=_viewModel.StorageHealth,AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false,Height=220,Margin=new Thickness(0,10,0,0)};dg.Columns.Add(new DataGridTextColumn{Header="장치",Binding=new Binding("Device"),Width=new DataGridLength(2,DataGridLengthUnitType.Star)});dg.Columns.Add(new DataGridTextColumn{Header="상태",Binding=new Binding("Status"),Width=90});dg.Columns.Add(new DataGridTextColumn{Header="온도",Binding=new Binding("Temperature"),Width=80});dg.Columns.Add(new DataGridTextColumn{Header="마모",Binding=new Binding("Wear"),Width=100});dg.Columns.Add(new DataGridTextColumn{Header="읽기/쓰기 오류",Binding=new Binding("ReadErrors"){StringFormat="{0}"},Width=120});content.Children.Add(dg);var battery=new TextBlock{Margin=new Thickness(0,12,0,0),Foreground=new SolidColorBrush(Color.FromRgb(82,90,102))};battery.SetBinding(TextBlock.TextProperty,new Binding(nameof(TelemetryV4ViewModel.BatteryText)));content.Children.Add(battery);ReportPage.Children.Add(health);
        var history=Panel();history.Margin=new Thickness(0,12,0,0);var historyStack=new StackPanel();history.Child=historyStack;historyStack.Children.Add(Heading("SQLITE BENCHMARK HISTORY · 30-DAY TELEMETRY"));var status=new TextBlock{Foreground=new SolidColorBrush(Color.FromRgb(104,112,125)),FontSize=10,Margin=new Thickness(0,5,0,10)};status.SetBinding(TextBlock.TextProperty,new Binding(nameof(TelemetryV4ViewModel.HistoryStatus)));historyStack.Children.Add(status);var hg=CreateHistoryGrid();hg.Height=240;historyStack.Children.Add(hg);ReportPage.Children.Add(history);
        InitializeLocalBenchmarkComparison();
    }
    private DataGrid CreateHistoryGrid(){var g=new DataGrid{ItemsSource=_viewModel.BenchmarkHistory,AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false};g.Columns.Add(new DataGridTextColumn{Header="측정 시각",Binding=new Binding("MeasuredAt"){StringFormat="yyyy-MM-dd HH:mm"},Width=150});g.Columns.Add(new DataGridTextColumn{Header="종합",Binding=new Binding("Score"),Width=75});g.Columns.Add(new DataGridTextColumn{Header="등급",Binding=new Binding("Grade"),Width=60});g.Columns.Add(new DataGridTextColumn{Header="CPU",Binding=new Binding("CpuScore"),Width=70});g.Columns.Add(new DataGridTextColumn{Header="MEM",Binding=new Binding("MemoryScore"),Width=70});g.Columns.Add(new DataGridTextColumn{Header="DISK",Binding=new Binding("DiskScore"),Width=70});g.Columns.Add(new DataGridTextColumn{Header="GPU",Binding=new Binding("GpuScore"),Width=70});g.Columns.Add(new DataGridTextColumn{Header="비교",Binding=new Binding("Difference"),Width=new DataGridLength(1,DataGridLengthUnitType.Star)});return g;}
    private static Border Panel()=>new(){Background=Brushes.White,BorderBrush=new SolidColorBrush(Color.FromRgb(222,226,232)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(5),Padding=new Thickness(18)};
    private static TextBlock Heading(string text)=>new(){Text=text,FontSize=11,FontWeight=FontWeights.SemiBold};
    private static FrameworkElement Metric(string title,string textBinding,string scoreBinding,string color){var s=new StackPanel{Margin=new Thickness(0,16,0,0)};var row=new Grid();row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});row.Children.Add(new TextBlock{Text=title,FontSize=11});var value=new TextBlock{FontFamily=new FontFamily("Consolas"),FontSize=11};value.SetBinding(TextBlock.TextProperty,new Binding(textBinding));Grid.SetColumn(value,1);row.Children.Add(value);s.Children.Add(row);var bar=new ProgressBar{Maximum=2000,Height=6,Margin=new Thickness(0,7,0,0),Foreground=(Brush)new BrushConverter().ConvertFromString(color)!};bar.SetBinding(RangeBase.ValueProperty,new Binding(scoreBinding){Mode=BindingMode.OneWay});s.Children.Add(bar);return s;}
    private static Button Action(string text,RoutedEventHandler click,string background="#181B20",string foreground="#FFFFFF"){var b=new Button{Content=text,Padding=new Thickness(16,9,16,9),Margin=new Thickness(0,0,8,0),BorderThickness=new Thickness(0),Background=(Brush)new BrushConverter().ConvertFromString(background)!,Foreground=(Brush)new BrushConverter().ConvertFromString(foreground)!,Cursor=Cursors.Hand};b.Click+=click;return b;}
    private void ForceProgressBindingsOneWay(){foreach(var p in Descendants<ProgressBar>(this)){if(BindingOperations.GetBinding(p,RangeBase.ValueProperty)is not Binding b||b.Path is null)continue;p.SetBinding(RangeBase.ValueProperty,new Binding(b.Path.Path){Mode=BindingMode.OneWay});}}
    private static IEnumerable<T> Descendants<T>(DependencyObject root)where T:DependencyObject{foreach(var child in LogicalTreeHelper.GetChildren(root).OfType<DependencyObject>()){if(child is T match)yield return match;foreach(var nested in Descendants<T>(child))yield return nested;}}
    private async void OnLoaded(object sender,RoutedEventArgs e){try{await _viewModel.InitializeAsync(_monitorCancellation.Token);_monitorTask=MonitorLoopAsync(_monitorCancellation.Token);}catch(OperationCanceledException){}catch(Exception ex){MessageBox.Show(this,ex.Message,"초기화 오류",MessageBoxButton.OK,MessageBoxImage.Warning);}}
    private async Task MonitorLoopAsync(CancellationToken token){using var timer=new PeriodicTimer(TimeSpan.FromMilliseconds(500));while(await timer.WaitForNextTickAsync(token)){if(_benchmarkActive)continue;try{await _viewModel.RefreshMetricsAsync(token);CheckAlerts();}catch(OperationCanceledException)when(token.IsCancellationRequested){break;}catch{}}}
    private void CheckAlerts(){if(DateTimeOffset.Now-_lastAlert<TimeSpan.FromMinutes(5))return;static double First(string s)=>double.TryParse(new string(s.TakeWhile(c=>char.IsDigit(c)||c=='.').ToArray()),NumberStyles.Float,CultureInfo.InvariantCulture,out var v)?v:0;var cpu=First(_viewModel.CpuValue);var memory=First(_viewModel.MemoryDetail);var tempText=_viewModel.TemperatureValue.Replace("CPU ","");var temperature=First(tempText);string? warning=cpu>=95?$"CPU 사용률이 {cpu:0}%입니다.":memory>=90?$"메모리 사용률이 {memory:0}%입니다.":temperature>=90?$"CPU 온도가 {temperature:0}°C입니다.":null;if(warning is null)return;_lastAlert=DateTimeOffset.Now;_tray.ShowBalloonTip(5000,"System Checker 경고",warning,Forms.ToolTipIcon.Warning);}
    private void Navigate_Click(object sender,RoutedEventArgs e){if(sender is not Button b||b.CommandParameter is not string page)return;OverviewPage.Visibility=page=="Overview"?Visibility.Visible:Visibility.Collapsed;HardwarePage.Visibility=page=="Hardware"?Visibility.Visible:Visibility.Collapsed;BenchmarkPage.Visibility=page=="Benchmark"?Visibility.Visible:Visibility.Collapsed;ReportPage.Visibility=page=="Report"?Visibility.Visible:Visibility.Collapsed;OverviewNav.Tag=page=="Overview"?"Active":null;HardwareNav.Tag=page=="Hardware"?"Active":null;BenchmarkNav.Tag=page=="Benchmark"?"Active":null;ReportNav.Tag=page=="Report"?"Active":null;PageTitle.Text=page.ToUpperInvariant();}
    private void ToggleSidebar_Click(object sender,RoutedEventArgs e){_sidebarCollapsed=!_sidebarCollapsed;SidebarColumn.Width=new GridLength(_sidebarCollapsed?0:226);}
    private async void RunBenchmark_Click(object sender,RoutedEventArgs e){_benchmarkCancellation?.Dispose();_benchmarkCancellation=new();_benchmarkActive=true;try{var previousMeasurement=_viewModel.LastBenchmark?.MeasuredAt;await _viewModel.RunBenchmarkAsync(_benchmarkCancellation.Token);if(_viewModel.LastBenchmark is{} current&&current.MeasuredAt!=previousMeasurement)await RefreshLocalComparisonAsync(true,_benchmarkCancellation.Token);}catch(Exception ex){MessageBox.Show(this,ex.Message,"벤치마크 오류",MessageBoxButton.OK,MessageBoxImage.Error);}finally{_benchmarkActive=false;}}
    private void CancelBenchmark_Click(object sender,RoutedEventArgs e)=>_benchmarkCancellation?.Cancel();
    private async void Export_Click(object sender,RoutedEventArgs e){var d=new SaveFileDialog{Filter="JSON 파일 (*.json)|*.json",FileName=$"system-report-{DateTime.Now:yyyyMMdd-HHmmss}.json"};if(d.ShowDialog(this)!=true)return;try{await _viewModel.ExportJsonAsync(d.FileName);Done();}catch(Exception ex){Error(ex);}}
    private void ExportPdf_Click(object sender,RoutedEventArgs e){var d=new SaveFileDialog{Filter="PDF 파일 (*.pdf)|*.pdf",FileName=$"system-report-{DateTime.Now:yyyyMMdd-HHmmss}.pdf"};if(d.ShowDialog(this)!=true)return;try{_viewModel.ExportPdf(d.FileName);Done();}catch(Exception ex){Error(ex);}}
    private void ExportHtml_Click(object sender,RoutedEventArgs e){var d=new SaveFileDialog{Filter="HTML 파일 (*.html)|*.html",FileName=$"system-report-{DateTime.Now:yyyyMMdd-HHmmss}.html"};if(d.ShowDialog(this)!=true)return;try{_viewModel.ExportHtml(d.FileName);Done();}catch(Exception ex){Error(ex);}}
    private async void RefreshHealth_Click(object sender,RoutedEventArgs e){try{await _viewModel.RefreshHealthAsync(_monitorCancellation.Token);}catch(Exception ex){Error(ex);}}
    private void Done()=>MessageBox.Show(this,"보고서를 저장했습니다.","완료");private void Error(Exception ex)=>MessageBox.Show(this,ex.Message,"오류",MessageBoxButton.OK,MessageBoxImage.Error);
    private void RestartElevated_Click(object sender,RoutedEventArgs e){try{var executable=Environment.ProcessPath??throw new InvalidOperationException("실행 파일 경로를 찾을 수 없습니다.");Process.Start(new ProcessStartInfo(executable){UseShellExecute=true,Verb="runas"});_allowClose=true;Close();}catch(Win32Exception ex)when(ex.NativeErrorCode==1223){}catch(Exception ex){Error(ex);}}
    private void HideToTray(){Hide();_tray.ShowBalloonTip(2500,"System Checker","백그라운드에서 모니터링 중입니다.",Forms.ToolTipIcon.Info);}private void RestoreFromTray(){Show();WindowState=WindowState.Normal;Activate();}
    private void TitleBar_MouseLeftButtonDown(object sender,MouseButtonEventArgs e){if(e.ChangedButton==MouseButton.Left){if(e.ClickCount==2)ToggleMaximize();else DragMove();}}private void Minimize_Click(object sender,RoutedEventArgs e)=>HideToTray();private void Maximize_Click(object sender,RoutedEventArgs e)=>ToggleMaximize();private void ToggleMaximize()=>WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;private void Close_Click(object sender,RoutedEventArgs e){_allowClose=true;Close();}
    private async void OnClosed(object? sender,EventArgs e){_monitorCancellation.Cancel();_benchmarkCancellation?.Cancel();if(_monitorTask is not null)try{await _monitorTask;}catch(OperationCanceledException){} _tray.Visible=false;_tray.Dispose();_benchmarkCancellation?.Dispose();_monitorCancellation.Dispose();_viewModel.Dispose();}
}

