using Microsoft.Win32;
using System.Diagnostics;
using System.Reflection;
using Forms=System.Windows.Forms;
namespace CoreWatch.Installer;
internal static class Program
{
    private const string Product="CoreWatch";private const string Version="5.0.0";
    [STAThread]private static void Main(string[] args){try{if(args.Contains("--uninstall",StringComparer.OrdinalIgnoreCase)){Uninstall();return;}Install();}catch(Exception ex){Forms.MessageBox.Show(ex.Message,"CoreWatch 설치 오류",Forms.MessageBoxButtons.OK,Forms.MessageBoxIcon.Error);}}
    private static void Install(){if(Forms.MessageBox.Show("CoreWatch를 현재 사용자 계정에 설치하시겠습니까?","CoreWatch Setup",Forms.MessageBoxButtons.YesNo,Forms.MessageBoxIcon.Question)!=Forms.DialogResult.Yes)return;var dir=InstallDirectory();Directory.CreateDirectory(Path.Combine(dir,"tools"));Directory.CreateDirectory(Path.Combine(dir,"Assets"));Extract("Payload.CoreWatch.exe",Path.Combine(dir,"CoreWatch.exe"));Extract("Payload.diskspd.exe",Path.Combine(dir,"tools","diskspd.exe"));Extract("Payload.DiskSpd-EULA.txt",Path.Combine(dir,"tools","DiskSpd-EULA.txt"));Extract("Payload.CoreWatch.ico",Path.Combine(dir,"Assets","CoreWatch.ico"));var self=Environment.ProcessPath??throw new InvalidOperationException("설치 프로그램 경로를 찾을 수 없습니다.");File.Copy(self,Path.Combine(dir,"CoreWatch-Uninstall.exe"),true);CreateShortcut(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu),"Programs","CoreWatch.lnk"),Path.Combine(dir,"CoreWatch.exe"));using var key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\CoreWatch");key.SetValue("DisplayName",Product);key.SetValue("DisplayVersion",Version);key.SetValue("Publisher","CoreWatch Project");key.SetValue("InstallLocation",dir);key.SetValue("DisplayIcon",Path.Combine(dir,"CoreWatch.exe"));key.SetValue("UninstallString",$"\"{Path.Combine(dir,"CoreWatch-Uninstall.exe")}\" --uninstall");key.SetValue("NoModify",1);key.SetValue("NoRepair",1);Forms.MessageBox.Show("CoreWatch 설치가 완료되었습니다.","CoreWatch Setup",Forms.MessageBoxButtons.OK,Forms.MessageBoxIcon.Information);Process.Start(new ProcessStartInfo(Path.Combine(dir,"CoreWatch.exe")){UseShellExecute=true});}
    private static void Uninstall(){if(Forms.MessageBox.Show("CoreWatch 프로그램 파일을 제거하시겠습니까?\n측정 기록 데이터베이스는 보존됩니다.","CoreWatch 제거",Forms.MessageBoxButtons.YesNo,Forms.MessageBoxIcon.Warning)!=Forms.DialogResult.Yes)return;var dir=InstallDirectory();var root=Path.GetFullPath(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Programs"))+Path.DirectorySeparatorChar;var full=Path.GetFullPath(dir);if(!full.StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("안전하지 않은 제거 경로입니다.");var shortcut=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu),"Programs","CoreWatch.lnk");if(File.Exists(shortcut))File.Delete(shortcut);Registry.CurrentUser.DeleteSubKeyTree(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\CoreWatch",false);Process.Start(new ProcessStartInfo("cmd.exe",$"/c timeout /t 2 /nobreak >nul & rmdir /s /q \"{full}\""){UseShellExecute=false,CreateNoWindow=true});}
    private static string InstallDirectory()=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Programs","CoreWatch");private static void Extract(string resource,string path){using var source=Assembly.GetExecutingAssembly().GetManifestResourceStream(resource)??throw new InvalidOperationException($"설치 리소스 누락: {resource}");using var target=File.Create(path);source.CopyTo(target);}private static void CreateShortcut(string path,string target){var type=Type.GetTypeFromProgID("WScript.Shell")??throw new InvalidOperationException("바로가기 서비스를 사용할 수 없습니다.");dynamic shell=Activator.CreateInstance(type)!;dynamic shortcut=shell.CreateShortcut(path);shortcut.TargetPath=target;shortcut.WorkingDirectory=Path.GetDirectoryName(target);shortcut.Description=Product;shortcut.Save();}
}

